CREATE TABLE answer_choices
(
    answer_id BIGINT NOT NULL,
    choice_id BIGINT NOT NULL,
    CONSTRAINT pk_answer_choices PRIMARY KEY (answer_id, choice_id)
);

CREATE TABLE answers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_id     BIGINT                                  NOT NULL,
    quiz_attempt_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_answers PRIMARY KEY (id)
);

CREATE TABLE choices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text        VARCHAR(255)                            NOT NULL,
    correct     BOOLEAN                                 NOT NULL,
    question_id BIGINT,
    CONSTRAINT pk_choices PRIMARY KEY (id)
);

CREATE TABLE match_pairs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_item VARCHAR(255)                            NOT NULL,
    target_item VARCHAR(255)                            NOT NULL,
    question_id BIGINT,
    CONSTRAINT pk_match_pairs PRIMARY KEY (id)
);

CREATE TABLE matching_answers
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_matching_answers PRIMARY KEY (id)
);

CREATE TABLE matching_questions
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_matching_questions PRIMARY KEY (id)
);

CREATE TABLE media
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename       VARCHAR(255),
    content_type   VARCHAR(255),
    data           OID                                     NOT NULL,
    uploaded_at    TIMESTAMP WITHOUT TIME ZONE,
    uploaded_by    BIGINT,
    reference_type VARCHAR(255),
    reference_id   BIGINT,
    CONSTRAINT pk_media PRIMARY KEY (id)
);

CREATE TABLE multiple_choice_answers
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_multiple_choice_answers PRIMARY KEY (id)
);

CREATE TABLE multiple_choice_questions
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_multiple_choice_questions PRIMARY KEY (id)
);

CREATE TABLE questions
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(255)                            NOT NULL,
    quiz_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE quiz_attempts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    quiz_id     BIGINT                                  NOT NULL,
    started_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    score       DOUBLE PRECISION,
    CONSTRAINT pk_quiz_attempts PRIMARY KEY (id)
);

CREATE TABLE quizzes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_quizzes PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE submitted_pairs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_item VARCHAR(255)                            NOT NULL,
    target_item VARCHAR(255)                            NOT NULL,
    answer_id   BIGINT,
    CONSTRAINT pk_submitted_pairs PRIMARY KEY (id)
);

CREATE TABLE true_false_answers
(
    id               BIGINT  NOT NULL,
    submitted_answer BOOLEAN NOT NULL,
    CONSTRAINT pk_true_false_answers PRIMARY KEY (id)
);

CREATE TABLE true_false_questions
(
    id             BIGINT  NOT NULL,
    correct_answer BOOLEAN NOT NULL,
    CONSTRAINT pk_true_false_questions PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE answers
    ADD CONSTRAINT FK_ANSWERS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE answers
    ADD CONSTRAINT FK_ANSWERS_ON_QUIZ_ATTEMPT FOREIGN KEY (quiz_attempt_id) REFERENCES quiz_attempts (id);

ALTER TABLE choices
    ADD CONSTRAINT FK_CHOICES_ON_QUESTION FOREIGN KEY (question_id) REFERENCES multiple_choice_questions (id);

ALTER TABLE matching_answers
    ADD CONSTRAINT FK_MATCHING_ANSWERS_ON_ID FOREIGN KEY (id) REFERENCES answers (id);

ALTER TABLE matching_questions
    ADD CONSTRAINT FK_MATCHING_QUESTIONS_ON_ID FOREIGN KEY (id) REFERENCES questions (id);

ALTER TABLE match_pairs
    ADD CONSTRAINT FK_MATCH_PAIRS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES matching_questions (id);

ALTER TABLE media
    ADD CONSTRAINT FK_MEDIA_ON_UPLOADED_BY FOREIGN KEY (uploaded_by) REFERENCES users (id);

ALTER TABLE multiple_choice_answers
    ADD CONSTRAINT FK_MULTIPLE_CHOICE_ANSWERS_ON_ID FOREIGN KEY (id) REFERENCES answers (id);

ALTER TABLE multiple_choice_questions
    ADD CONSTRAINT FK_MULTIPLE_CHOICE_QUESTIONS_ON_ID FOREIGN KEY (id) REFERENCES questions (id);

ALTER TABLE questions
    ADD CONSTRAINT FK_QUESTIONS_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES quizzes (id);

ALTER TABLE quizzes
    ADD CONSTRAINT FK_QUIZZES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE quiz_attempts
    ADD CONSTRAINT FK_QUIZ_ATTEMPTS_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES quizzes (id);

ALTER TABLE quiz_attempts
    ADD CONSTRAINT FK_QUIZ_ATTEMPTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE submitted_pairs
    ADD CONSTRAINT FK_SUBMITTED_PAIRS_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES matching_answers (id);

ALTER TABLE true_false_answers
    ADD CONSTRAINT FK_TRUE_FALSE_ANSWERS_ON_ID FOREIGN KEY (id) REFERENCES answers (id);

ALTER TABLE true_false_questions
    ADD CONSTRAINT FK_TRUE_FALSE_QUESTIONS_ON_ID FOREIGN KEY (id) REFERENCES questions (id);

ALTER TABLE answer_choices
    ADD CONSTRAINT fk_anscho_on_choice FOREIGN KEY (choice_id) REFERENCES choices (id);

ALTER TABLE answer_choices
    ADD CONSTRAINT fk_anscho_on_multiple_choice_answer FOREIGN KEY (answer_id) REFERENCES multiple_choice_answers (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);